In [1]:
###Q1)

In [3]:
import numpy as np

In [24]:
units_sold=np.array([11,23,44,65,87,98,32])
units_sold

array([11, 23, 44, 65, 87, 98, 32])

In [25]:
units_price=np.array([10,15,12,20,80,51,21])
sales=units_sold*units_price
sales

array([ 110,  345,  528, 1300, 6960, 4998,  672])

In [16]:
total_sales=np.sum(sales)
total_sales

14913

In [17]:
###2)

In [26]:
record=units_sold[units_sold>30]
record

array([44, 65, 87, 98, 32])

In [33]:
profits=np.array([1000,800,700,200,170,300,500])

filtered_profit=profits[units_sold>30]
avg_profit=np.mean(filtered_profit)

print(avg_profit)

374.0

In [ ]:
###Q3)

In [47]:
import pandas as pd

df = pd.read_csv("data.csv")

In [50]:
df.head()

,country,order_value_EUR,cost,date,category,customer_name,sales_manager,sales_rep,device_type,order_id
0,Sweden,"17,524.02",14122.61,2/12/2020,Books,Goldner-Dibbert,Maxie Marrow,Madelon Bront,Mobile,70-0511466
1,Finland,"116,563.40",92807.78,9/26/2019,Games,Hilll-Vandervort,Hube Corey,Wat Bowkley,Mobile,28-6585323
2,Portugal,"296,465.56",257480.34,7/11/2019,Clothing,Larkin-Collier,Celine Tumasian,Smitty Culverhouse,PC,58-7703341
3,Portugal,"74,532.02",59752.32,4/2/2020,Beauty,Hessel-Stiedemann,Celine Tumasian,Aurelie Wren,PC,14-6700183
4,Spain,"178,763.42",146621.76,12/22/2019,Games,Johns and Sons,Emalia Dinse,Bertha Walbrook,Tablet,15-8765160

In [51]:
df.dtypes

country               object
 order_value_EUR      object
 cost                float64
date                  object
category              object
customer_name         object
sales_manager         object
sales_rep             object
device_type           object
order_id              object
dtype: object

In [52]:
df.describe()

               cost
count    1000.000000
mean    94369.310990
std     51540.020934
min     12113.680000
25%     54247.957500
50%     87094.760000
75%    125570.837500
max    304701.430000

In [53]:
###Q4)

In [78]:
data = {
    "Product":["toys","Brush","Comb","Pen","Notebook"],
    "Region":["east","south","west","north","north"],
    "Units_Sold":[20,40,10,25,30],
    "Unit_Price":[450,10,20,7,70],
    "Profit": [500,30,50,10, 10]
}
data
Data=pd.DataFrame(data)

In [81]:
Data["Revenue"]=Data["Units_Sold"]*Data["Unit_Price"]
Data

    Product Region  Units_Sold  Unit_Price  Profit  Revenue
0      toys   east          20         450     500     9000
1     Brush  south          40          10      30      400
2      Comb   west          10          20      50      200
3       Pen  north          25           7      10      175
4  Notebook  north          30          70      10     2100

In [84]:
Data.groupby("Region")["Revenue"].sum()

Region
east     9000
north    2275
south     400
west      200
Name: Revenue, dtype: int64

In [85]:
Data.groupby("Product")["Profit"].sum().idxmax()

'toys'

In [ ]:
###Q6

In [86]:
Data.groupby("Product")["Unit_Price"].mean()

Product
Brush        10.0
Comb         20.0
Notebook     70.0
Pen           7.0
toys        450.0
Name: Unit_Price, dtype: float64

In [87]:
Data.groupby("Region")["Product"].count()

Region
east     1
north    2
south    1
west     1
Name: Product, dtype: int64

In [88]:
Data.groupby("Product")["Units_Sold"].max()

Product
Brush       40
Comb        10
Notebook    30
Pen         25
toys        20
Name: Units_Sold, dtype: int64

In [89]:
###Q7

In [90]:
Data[Data["Profit"] > 1000]

Empty DataFrame
Columns: [Product, Region, Units_Sold, Unit_Price, Profit, Revenue]
Index: []

In [91]:
Data["Revenue"] = Data["Units_Sold"] * Data["Unit_Price"]

In [92]:
Data.sort_values(by="Revenue", ascending=False)

    Product Region  Units_Sold  Unit_Price  Profit  Revenue
0      toys   east          20         450     500     9000
4  Notebook  north          30          70      10     2100
1     Brush  south          40          10      30      400
2      Comb   west          10          20      50      200
3       Pen  north          25           7      10      175

In [95]:
Data.loc[len(Data)] = ["Laptop","east",15,50000,5000,750000]

In [96]:
Data[Data["Product"] == "Laptop"]

  Product Region  Units_Sold  Unit_Price  Profit  Revenue
5  Laptop   east          15       50000    5000   750000
6  Laptop   east          15       50000    5000   750000